title: Lexicase Selection Documentation
description: lexicase.ai
theme: minima

# Site settings
url: "https://nlorant-s.github.io"
baseurl: "/lexicase.ai"

# Build settings
markdown: kramdown
highlighter: rouge

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Navigation
header_pages:
  - about.md
  - docs.md

# Exclude files from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - .gitignore
